### ISSUE TITLE
On Windows System Tray Pause / Start Folding isn't working

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#186]
Similar to #185.

![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/7a5eec5c-f5d0-42d5-9d0d-596baea8ea21)

Win10-FAH v8.3.0 (Debug), Builder file 113 from 2023-12-30.
Pressing the Pause / Start in the system tray control doesn't have the correct state (already not running and says 'Pause').

[Edited] --> FAH is not issuing the Fold/Pause commands in the log. It should have happened many times between viewing the log file, and there are no command entries:
```
12:54:37:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T12:54:37.868Z"}
12:54:39:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T12:54:39.731Z"}
12:54:41:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T12:54:41.555Z"}
12:55:40:I1:WU1365:Completed 25000 out of 2500000 steps (1%)
12:57:27:I1:WU1365:Completed 50000 out of 2500000 steps (2%)
12:57:29:I1:WU1365:Checkpoint completed at step 50000
12:57:50:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T12:57:50.749Z"}
12:58:15:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T12:58:15.952Z"}
12:59:06:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T12:59:06.536Z"}
12:59:16:I1:WU1365:Completed 75000 out of 2500000 steps (3%)
12:59:55:D3:msg: {"enable": false, "cmd": "log", "time": "2023-12-30T12:59:55.842Z"}
12:59:58:D3:msg: {"enable": true, "cmd": "log", "time": "2023-12-30T12:59:58.804Z"} 
```

[Added] --> Testing this again with the latest Windows (Debug) builder file 116, using Firefox, I get the same behavior:
If logged out, then Pause/Resume works correctly locally.
When logged-in, then you get nothing pressing either the main Fold or Pause buttons, locally or remote.

**Comment by jcoffland** [comment]
No fold/pause commands are issued to the account via the sys-tray icon.  The Windows sys-tray icon only controls the local client.  It does not have access to the account login.  Therefore, you will not see fold/pause commands in the log.

The error your describing doesn't make sense to me since being logged in or not only affects web control and the sys-tray only affects fah-client.  I also tested this and I cannot reproduce the problem.

Is this still an issue?

**Comment by Hou5e** [comment]
Latest Win Debug build 117 with Firefox:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/07c65626-85a6-4774-b8df-e581215fdd0d)

With a WU started, click the Pause Now button for the local PC only control. The system tray still says 'Pause' when it is paused. Pressing 'Pause' in the system tray starts folding again. When the WU is running, the system tray 'Pause' command doesn't work to stop folding.

If you can't reproduce this, then you may need the steps in #185 for the logged-in messed-up state that can't access remotes. But I don't think it's required to be logged-in for this issue of the system tray Pause/Fold.

**Comment by jcoffland** [comment]
This should be fixed in the latest build.

**Comment by jcoffland** [comment]
Windows shouldn't be showing the certificate dialog at all.  I'm pretty confident that the node server now does not request client certificates.

**Comment by Hou5e** [comment]
It reproduces this issue without the certificate dialog:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/7a5b26cf-24cf-4be5-879f-56aab794a122)
From the system tray in that state, you can press Pause twice to get it to resume folding.

**Comment by jcoffland** [comment]
The picture looks correct to me.  Groups Default and /RG1 are not paused.  If anything is unpaused, sys-tray considers the client to be folding, even though those groups don't have any resources.  Pressing the "Pause" twice first pauses all the groups then unpauses all of them.

I see how this is confusing though.  We'd be better off having two buttons.  This is why there are two buttons at the top of Web Control rather than one that changes state.

**Comment by jcoffland** [comment]
Latest build uses two sys-tray buttons.

**Comment by Hou5e** [comment]
That change works well.
