### ISSUE TITLE
On Windows with Chrome / MS Edge / Opera, must cancel 'Select a Certificate' dialog

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#188]
On Windows with Chrome (or MS Edge, or Opera), there is 'Select a Certificate' dialog on initial FAH loading when logged-in.
Clicking OK, you are continuously prompted with the dialog, until you click cancel, and then it seems to just work. If you close the browser and reopen it to that page, then the 'Select a Certificate' dialog comes back.

![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/76cc882b-c894-4a87-9e9f-14b488627588)

After clicking: Cancel
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/44a25c0d-8162-47d4-808b-9356442e337a)

---
MS Edge (Chrome / Chromium-based) is similar:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/9af2dacb-e4e3-4b2c-93bb-b706fdd12f33)

After clicking: Cancel
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/fdcaa0e6-0bde-4136-be4c-2513d2cb116f)

---
Opera (Chrome / Chromium-based) is similar, too:
![image](https://github.com/FoldingAtHome/fah-client-bastet/assets/20870053/a0fa5e50-df65-48ed-bbcc-a21be9214c1f)

**Comment by jcoffland** [comment]
I did some research on this.  It is caused by a combination of two things.

1. You have an autogenerated certificate issued by ``MS-Organization-Access`` on your machine.
2. node1.foldingathome.org accepts SSL client certificates.

The certificate on your machine is created by Active Directory Federation Services (ADFS).  You can safely delete it but an new one will be generated next time you access Azure or some other ADFS.

F@H nodes are configured to accept client certificates because that is how clients authenticate with the node.  I'm hoping there's a way to tell the browser to not offer client certificates via Javascript but it may not be possible.

The only other option would be to make clients and browsers use different ports to connect to the node.  This would either require the node to have two IPv4 addresses or clients or web control to connect on a non-standard port.  Non-standard ports are often blocked by corporate or university firewalls so that's not a great option.

**Comment by jcoffland** [comment]
It turns out the client don't need client certificates when connecting to the node.  I've disabled this feature on the node.  The problem should now be fixed.

**Comment by Hou5e** [comment]
Yep, that fixed this issue. After a refresh without cache, the dialog doesn't show up anymore. 🙂

**Comment by Hou5e** [comment]
This issue is back today

**Comment by Hou5e** [comment]
This was fixed yesterday.
