### ISSUE TITLE
HideConsole.exe tries to interact with files well outside its lane

### ISSUE THREAD

**Issue by dymil** [FoldingAtHome/fah-client-bastet#227]
My security software Norton is throwing a hissy fit trying to protect files from being accessed by the F@H alpha client, including Firefox's AppData folder and `.part` in-progress downloads (from Firefox); I think the reaction from Norton is then preventing the download from completing. I have to exit the client entirely (not just pause folding) to complete the downloads in question.

Running v8.3.3 on Windows 10. Quick searching here and in the web client repo didn't find any leads on this.

**Comment by kbernhagen** [comment]
Probably won't solve your problem, but please try the latest beta:
https://foldingathome.org/beta/

**Comment by dymil** [comment]
Confirmed the behavior is unchanged. Also, I think it would be nice to redirect the beta page to the alpha one then.

**Comment by jcoffland** [comment]
HideConsole.exe is a very simple program.  All it does is prevent a console from popping up when a core is run.  It doesn't try to access any external files.  It's source code can be seen right here: https://github.com/FoldingAtHome/fah-client-bastet/blob/master/src/HideConsole.cpp  It does execute a sub-process which makes Windows system calls that could be searching the system PATH.  But this is a pretty typical thing for a program to do.  I don't see how this is not Norton's fault or maybe a misinterpretation of the logs.  Unless you some how have a different HideConsole.exe than the one we publish.

I'm closing this because I don't see any action we can take with out more evidence.
