### ISSUE TITLE
Display of PPD in the web interface

### ISSUE THREAD

**Issue by Shaeric** [FoldingAtHome/fah-client-bastet#244]
The placement of the PPD column confused me at first.

All other group specific columns (Project, CPUs, GPUs, Status, Progress, ETA and Actions) relate to WU-specific rows.
Perhaps instead of PPD either the old Estimate Credit or Base Credit could be displayed in each row as they are related
to the current WU and PPD could instead be displayed in the machine row above the group table as sum total.

That would clarify the actual PPD a machine can output, while at the same time giving the user a grasp
of how "big" each individual unit is, as was the case in the old client.

**Comment by jcoffland** [comment]
This issue should be in fah-web-client-bastet as it relates to the frontend.  Removing PPD would upset a lot of people as this is the metric most important to many.  Base credit or estimated credit don't tell you much alone because it depends a lot on how log the WU takes to complete.

See also: https://github.com/FoldingAtHome/fah-web-client-bastet/issues/128

Please open a new issue in fah-web-client-bastet if you think there something not covered by the existing issues.
