### ISSUE TITLE
Local client does not reconnect to Web Control for some time after reinstall or client restart.

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#287]
So I moved my farm to v8.4.4. Last to go was main PC with Win 11.
Firstly launching installer triggered Windows Defender SmartScreen, which I am not worried about and told it to install anyways. Installation went smooth. After installation web control launched, and I saw other 3 PCs, but not the local one. web control has already logged in, since this PC have seen v8 in previous itterations. Systray icon shows fahlient paused. I can see fahclient.exe in Task Manager. When I click `Fold` through systray icon, nothing happens.
Here is the log:
```
*********************** Log Started 2024-09-14T21:36:57Z ***********************
21:36:57:I1:*********************** Folding@home Client ***********************
21:36:57:I1:    Version: 8.4.4
21:36:57:I1:     Author: Joseph Coffland <joseph@cauldrondevelopment.com>
21:36:57:I1:        Org: foldingathome.org
21:36:57:I1:  Copyright: 2023-2024, foldingathome.org
21:36:57:I1:   Homepage: https://foldingathome.org/
21:36:57:I1:    License: GPL-3.0-or-later
21:36:57:I1:        URL: https://v8-4.foldingathome.org/
21:36:57:I1:       Date: Aug 27 2024
21:36:57:I1:       Time: 14:43:45
21:36:57:I1:   Revision: d071d0df1c1a752022e4d12dd4353eeb7eafcf83
21:36:57:I1:     Branch: master
21:36:57:I1:   Compiler: Visual C++
21:36:57:I1:    Options: $( /TP $) /std:c++14 /nologo /EHa /wd4297 /wd4103 /O2
21:36:57:I1:             /Zc:throwingNew /MT
21:36:57:I1:   Platform: win32 10
21:36:57:I1:       Bits: 64
21:36:57:I1:       Mode: Release
21:36:57:I1:       Args: --open-web-control
21:36:57:I1:****************************** CBang ******************************
21:36:57:I1:    Version: 1.7.2
21:36:57:I1:     Author: Joseph Coffland <joseph@cauldrondevelopment.com>
21:36:57:I1:        Org: Cauldron Development
21:36:57:I1:  Copyright: Cauldron Development, 2003-2024
21:36:57:I1:   Homepage: https://cauldrondevelopment.com/
21:36:57:I1:    License: LGPL-2.1-or-later
21:36:57:I1:       Date: Aug 27 2024
21:36:57:I1:       Time: 14:43:06
21:36:57:I1:   Revision: bbfff7de9fa54453f942b7f1489df6a36fee7a3b
21:36:57:I1:     Branch: master
21:36:57:I1:   Compiler: Visual C++
21:36:57:I1:    Options: $( /TP $) /std:c++14 /nologo /EHa /wd4297 /wd4103 /O2
21:36:57:I1:             /Zc:throwingNew /MT
21:36:57:I1:   Platform: win32 10
21:36:57:I1:       Bits: 64
21:36:57:I1:       Mode: Release
21:36:57:I1:***************************** System ******************************
21:36:57:I1:        CPU: AMD Ryzen 9 7950X3D 16-Core Processor
21:36:57:I1:     CPU ID: AuthenticAMD Family 25 Model 97 Stepping 2
21:36:57:I1:       CPUs: 32
21:36:57:I1:     Memory: 31.62GiB
21:36:57:I1:Free Memory: 20.96GiB
21:36:57:I1: OS Version: 6.2
21:36:57:I1:Has Battery: false
21:36:57:I1: On Battery: false
21:36:57:I1:   Hostname: muziqazPC
21:36:57:I1: UTC Offset: 1
21:36:57:I1:        PID: 33904
21:36:57:I1:        CWD: C:\ProgramData\FAHClient
21:36:57:I1:       Exec: C:\Program Files\FAHClient\FAHClient.exe
21:36:57:I1:*******************************************************************
21:36:57:I2:<config/>
21:36:57:I1:Opening Database
21:36:57:I1:F@H ID = I1HR9qrjkwkgle82-gtCry74Fc1GeZ-n5iDxMr4iyJs
21:36:57:I3:Loading default group
21:36:57:I3:Loading default resource group
21:36:57:I1:Listening for HTTP on 127.0.0.1:7396
21:36:57:I3:Loaded 0 wus.
21:36:57:E :Subprocess deallocated while process is still running
21:36:57:I1:Started Windows systray control
21:36:57:I3:gpus = {
21:36:57:I3:  "gpu:03:00:00": {
21:36:57:I3:    "vendor": 4098,
21:36:57:I3:    "type": "amd",
21:36:57:I3:    "description": "gfx1100",
21:36:57:I3:    "opencl": {"platform": 0, "device": 0, "compute": "2.0", "driver": "3628.0"},
21:36:57:I3:    "device": 29772,
21:36:57:I3:    "supported": true
21:36:57:I3:  }
21:36:57:I3:}
```
I reinstalled the client few times, reloaded browser page. Nothing.
Ok, now I clicked `Fold` through systray, and it downloaded fahcore_a8 WU. I still cannot see this client neither locally, nor through remote clients (other PCs).
This is on Firefox.
I just launched Edge, which I never use, and I can see local fahclient :/
Firefox private browsing still does not see it. In that mode, Firefox is not using any existing cache or cookies.
I logged in to my account through Edge, and pop up showed up saying that client has been linked to an account. And I see all 4 of my machines through edge, however, remote Linux Firefox threw an error: `Loggin in failed. API: error: TypeError: NetworkError when attempting to fetch resource.` After clicking ok, remote PC still cannot see Win11 machine.
Reloading remote Linux browser few times finally saw win 11 client.
Local Firefox can also finally see all machines including itself.

I'm not really sure how this can be reproduced and tested and fixed :D This is some weird stuff.

**Comment by jcoffland** [comment]
Is it possible you didn't wait long enough?  You must either pass the account token on the command line or login to your account with a local browser and wait for the browser to actually connect to the local client.  Otherwise, the client will not be connected to your account.  If you do a full reinstall of the client, i.e. wipe all it's data, then you must do this all over again for that machine.

Web Control now pops up a message when it auto links the machine to your account.  If you don't see this popup in Web Control after a fresh install or after a reinstall that wipes the data, then the machine is not linked.

**Comment by muziqaz** [comment]
The pop up did not show up until fourth try and only when Edge was used.
In all these tries I did give some time for client to react.
My sequence was this:
Install the client on Win11, I got auto logged into my account, no pop up showed up, so then I turned to my other monitor which is displaying Linux machine, which is monitoring the whole farm. So that in itself is a while. I refreshed Linux browser few times.
Once I reinstalled win 11 client few times, on Linux machine I even launched Vivaldi browser to check. So all these actions should have given enough time for client and account to see each other and link.
For more context:
The first try was upgrade from v7, and I used v7 fahdata folder. So my initial thoughts was that this folder might be an issue. So I reinstalled the client, but this time I left all directories default. Still had same issue.
Also of note: fahclient installer does not seem to realise that there is already v8 fahclient installed on the system. I'm used to installers seeing software already installed and tell me - do I want to repair, or reinstall, or uninstall, or abort. It also kept suggesting default fahdata folder even though during previous install I chose my own fahdata directory. But that is not related to the issue, just an observation

**Comment by jcoffland** [comment]
> My sequence was this: Install the client on Win11, I got auto logged into my account, no pop up showed up

This is where you need to wait.  If the browser is already open when you do the client install, it can take some time for it to connect to the local client.  I've tried to speed this up but the browser's connection retry logic makes this difficult.

> so then I turned to my other monitor which is displaying Linux machine, which is monitoring the whole farm. So that in itself is a while. I refreshed Linux browser few times.

This will not help.  As long as the client is not linked to your account you will not be able to see it from any remote machine.

> Once I reinstalled win 11 client few times, on Linux machine I even launched Vivaldi browser to check. So all these actions should have given enough time for client and account to see each other and link.

Every time you reinstall you're starting over and only increasing the delay.

I think the whole problem here is that the browser takes longer than expected to connect to the local client.  The only thing you can do is wait.  Reloading the browser or reinstalling will just increase the delays.  The only thing that might help is to completely exit the browser and restart it after the client has been installed.  Otherwise, the browser's retry logic gets in the way.

**Comment by jcoffland** [comment]
I believe this problem is caused by this sequence of events:

1) Local client is running and Web Control is open and connected.
2) Client shuts down.
3) Web Control connection to local client is dropped.
4) Web Control continues to try to connect to the local client.  This increases it's error count and retry delay.  This delay is internal to the browser and may even affect private windows.
5) The local client comes back either because it was restarted or reinstalled, new version or otherwise.
6) Web Control fails to connect to the local client for up to a minute.  Any "help" from the user at this point tends to just make things worse and delay the connection even longer.
7) Eventually, if left alone, the connection is restored after some delay.

I'm not sure what the solution is here.  There's no way for the local client to signal Web Control when it's ready for a connection and when not.  The only thing you can do is try to connect and then try again.  This triggers the browsers connection back off logic which is out of our control.

This problem is further complicated because Web Control does not know if the local client is supposed to be there or not.  So warning the user via Web Control is useless because it would give the wrong indication in the case where there is no local client.

**Comment by muziqaz** [comment]
I'm back to the same issue.
I reset the FAH account password through new PC, while my main Windows PC was logged in and monitoring all the linked PCs, including itself. As soon as I changed the password. My main PC removed all the monitoring machines, and said that No machines are available, or something of the kind, as if my PC was not running FAH and the rest of the PCs were off.
So I logged out (it did not log out automatically). Logged back in with new password. And it was still saying no machines found.
I left it for a second. Linked my new PC to the Account, that showed up straight away on my main PC, while still not showing local fahclient (which is running, I see systray, which says active). 
I logged into my other Linux machine with new password, it was asked to Link that PC (which is weird, since that PC was linked before and was running). So I linked it, it showed up immediately on my Main PC, which still is not showing my local client.
Firefox console is showing this repeatedly every 5-10 seconds:
```
Firefox can’t establish a connection to the server at ws://127.0.0.1:7396/api/websocket. index-98a3114b.js:3643:21740
The connection to ws://127.0.0.1:7396/api/websocket was interrupted while the page was loading.
```
While these errors are showing up I am not touching web UI at all.

Closing Firefox FAH web ui TAB and relaunching it from systray icon does not do any good. This PC is not showing up on my other PCs too.
My other Windows PC did not log out after password change. Browser was closed during password change, so When I launched Web UI, it loaded logged in. It said that PC is unlinked. It allowed me to link that PC while being logged in with old password. Clicking log out did nothing, had to reload the page, and it still showed half loaded account page, and only when I clicked Close button in Account page it finally showed that I was logged out.
While I'm writing all this, main PC client has not showed up anywhere yet

**Comment by jcoffland** [comment]
This is expected.  If you reset your password you need to read the fine print.  Or rather the clear print.  In the process of resetting Web Control tells you that you must manually reconnect all of your machines after the reset.  This is due to how the F@H account security works.

**Comment by jcoffland** [comment]
This is expected.  If you reset your password you need to read the fine print.  Or rather the clear print.  In the process of resetting Web Control tells you that you must manually reconnect all of your machines after the reset.  This is due to how the F@H account security works.

You simply have to wait longer for the local client to connect.  Wait with out refreshing the browser or logging in and out or any similar actions.

**Comment by jcoffland** [comment]
This is really a Web Control issue that belongs in fah-web-client-bastet issues.  Also, it's mostly a browser issue.

**Comment by jcoffland** [comment]
Issue moved.
