### ISSUE TITLE
FAHClient.exe high memory usage in Windows

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#291]
HI,
not sure if this is normal, or if there is some sort of memory leak. On Win 11 system FAHClient.exe is using quite a bit of RAM. client is not doing anything at this moment, I paused all the resource groups. System has 32GB of RAM
![fah mem usage](https://github.com/user-attachments/assets/b89ec17e-7251-42de-844d-7d2383533406)

One of the Windows 10 systems with 16GB of RAM is using 75.7MB of RAM, while it is folding fahcore_a8 WU (fahcore_a8 is using 143MB, which is fine)
Another Windows 10 system with 16GB of RAM is using 472MB of it, while folding an A8 WU.

None of those Windows machines have Web Control open.
On Linux, I can't even find fahclient among top 70 processes visible in console

**Comment by muziqaz** [comment]
It might be how Windows 11 reserves memory for the apps, but I thought I should bring it to your attention, just in case

**Comment by jcoffland** [comment]
That is strange.  I don't know why it would be different on Windows 11 vs. 10.

**Comment by muziqaz** [comment]
Well, Win 11 is kinda different beast in certain aspect. I wouldn't run past them to relax memory management to the point where it just reserves everything it sees :D

**Comment by muziqaz** [comment]
There is another report of Fahclient using 6GB of RAM at which point it runs out of available memory, and apparently takes down WU which is being worked on.

On a different note, windows 11 system, which I reported in original post here, is now showing 1.2MB of RAM used for Fahclient.exe. folding is paused at this moment.

**Comment by Demmersify** [comment]
I am the user who reported fahclient.exe using about 6GB of RAM. This was while running WU 18806 0xa9 before the WU crashed. Now currently running at 86MB with a 0xa8 WU.

Windows 11 Pro 23H2 Version 10.0.22631 Build 22631
MOBO: Gigabyte B450 I AORUS PRO WIFI
16GB RAM @ 3200MHz

FAH Logs System Info:
CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics @ 3700MHz
CPU ID: AuthenticAMD Family 23 Model 24 Stepping 1
CPUs: 8
Memory: 13.92GiB
Free Memory: 11.11GiB
Threads: WINDOWS_THREADS
OS Version: 6.2
Has Battery: false
On Battery: false

**Comment by Demmersify** [comment]
> Do you have any client logs you can post for this?

Unfortunately not, but however, in my case this was a false alarm anyway. It turned out the issue was down to myself having set virtual memory paging size to 0 during earlier experimenting before I decided to go back to folding. Because I wasn't noticing any issues since the change, I forgot to reset paging size to default. After I did reset it, by chance I got this same WU, and it went by without a problem. The fahclient.exe memory did increase somewhat (no where near as much as previously stated), but only because of how large this particular WU is. Any other WU and everything is running as expected.

**Comment by muziqaz** [comment]
I'll continue monitoring on my Windows machines, or if someone else reports similar behaviour. Hopefully those reports will not be influenced with some custom OS set ups :)

**Comment by KamikazeWombat** [comment]
I'm seeing this also.  I just upgraded from 16 GB to 32 GB RAM and while I don't remember how much FAHClient was using before I'm fairly sure it was less than 500MB.  Now it's using 6914.4 MB of RAM, in addition to the 1745 FahCore_a9 is using.  
I had version 8.3.18 when I noticed the problem, upgraded to 8.4.9 and still seeing this behavior.  It's not a critical problem for me since I really only needed another couple GB for my usage but I'm still not thrilled with FAH using almost half of the 16 GB I just added for no apparent purpose.  
None of my FAH log files seems to be from this year, not sure why.

**Comment by jcoffland** [comment]
@KamikazeWombat is this on Windows 11?

**Comment by KamikazeWombat** [comment]
Yes, this was Windows 11.  Strangely when I looked a day or two later it wasn't doing it anymore.  Tried a few things including rebooting the machine and it's currently using 21 MB of RAM.  I'm 99% sure I rebooted Windows before I made the post earlier this week to make sure it wasn't some silly fluke.  Not sure what the deal was, but I guess since it stopped we can't easily dig further.

**Comment by muziqaz** [comment]
![Image](https://github.com/user-attachments/assets/afa15f84-9a43-4841-a7a9-383b879705a9)

Here is comparison between Task Manager and Process Explorer. Both seem to show relatively similar numbers. Task Manager is even a bit conservative.
Process Explorer: 477MB
Task Manager: 442MB

**Comment by muziqaz** [comment]
ha,
so, pause a CPU or GPU WU, and restart the PC. Upon restart, open the task manager and observe fahclient use one full core and ramp up to 3GB of RAM in no time. Task manager also reports high HDD usage during that period. Eventually CPU usage drops, and HDD usage drops too, and RAM increase stops.

**Comment by muziqaz** [comment]
> > This probably needs to be re-opened.
> 
> Can you go ahead and re-open this?

I wasn't the one who closed it, so have no permission to re-open it

**Comment by wesgeorge** [comment]
@jcoffland can you reopen this please?

**Comment by wesgeorge** [comment]
since this issue is closed, and we've had no luck getting it reopened, let alone investigated for a fix, I just created a new issue 376. Please post additional info, including logs in that issue.

**Comment by muziqaz** [comment]
Thanks, though this issue will have to be investigated anyways, as we can reproduce this very easily
