### ISSUE TITLE
Linux: Supported GPU not recognised wo/ GPU driver packages installed.

### ISSUE THREAD

**Issue by tysox** [FoldingAtHome/fah-client-bastet#293]
I had to run the command
`sudo apt install ocl-icd-opencl-dev`
in order for my supported GPU to be triggered as actually supported in the FAH client.
It would be convenient if GPUs could just be supported straight away without further configuration; apparently this has been a long-standing issue on Linux?

More details [here](https://foldingforum.org/viewtopic.php?t=41383#)

P.S.: the v8.3 client is _so_ much better for running FAH on Linux now :) **Thank you!**

**Comment by muziqaz** [comment]
That is in a way AMDs fault and the way Linux works. Unfortunately doubt FAH would be able to implement this on a global scale across the distros.
I have installed 7 or 8 different distros for FAH testing purposes on variety of AMD hardware, and every single distro has its own issue, unfortunately. What is worse, now newer distro versions are outright removing ROCm packages for some unknown reason, so users have to actually fish that from depths of the Linux hell. Case in point Fedora 38 had rocm-opencl-sdk in its repos, which enabled FAH folding right away. Fedora 40 removed that, and suggested that user compiles ROCm from the source.
Linux Mint 21 was folding right out of the box with AMD driver installation.
Linux Mint 22 is a struggle now to get things going since again I have to fish for ROCm packages :(
But overall all ICD packages usually trigger the exposure of AMD hardware and OpenCL platform to FAH.
And wait till you try v8.4+ FAH client, that is even more awesome ;)

**Comment by jcoffland** [comment]
The package should suggest or recommend the GPU driver packages.

**Comment by jcoffland** [comment]
It's not a great idea to have our package depend on a ``-dev`` package.  Is installing just ``ocl-icd-libopencl1`` sufficient?
