### ISSUE TITLE
Improve error communication with end user

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#299]
With v8, users seem to be oblivious that there might have been some sort of failure. We definitely need some sort of communication idea. Maybe pop up when user opens web UI? Pop up would have time stamp and error displayed.

**Comment by muziqaz** [comment]
Or maybe notification section, which lights up in case of errors, failed WUs, etc
This includes all the CUDA/OpenCL/HIP platform issues users are getting and fahclient dumps the WU without warning if you are not around.

**Comment by jhitze** [comment]
I agree with you. There are the logs available, with error & warning filters, which is what I use right now.

**Comment by jcoffland** [comment]
If only the software were smart enough to diagnose the problem and respond with sound advice for the user.  The thing is, if you know exactly what the problem is then you could just fix it instead of telling the user.

Note,  you must also be able to avoid showing the wrong error message for issues with similar symptoms.  For example, lacking OpenCL support is totally normal if you don't have a GPU.  So you shouldn't popup an error message every time OpenCL is missing.

This issue is too vague.  If you have a specific error scenario that could be reported better please open a new issue.

**Comment by muziqaz** [comment]
Notification of failed or dumped WU would be a start.
As I mentioned somewhere else, there is a massive amount of V8 users who are simply oblivious of incredible numbers of failures their Fahclient produces. Some might be ignorant by choice, others are simply not aware.
This issue is so widespread that one of the researchers had to even stop their project due to nearly all of their WUs come back failed.
You probably received few emails from some of the researchers, too. We very rarely have this kind of issue, where researchers are coming back to us and mentioning some crazy failure rates.

**Comment by jcoffland** [comment]
This particular issue is already fixed in v8 alpha.  We just need to get the alpha to public release ASAP.
