### ISSUE TITLE
When I force to max CPU core, 2 WU started

### ISSUE THREAD

**Issue by Adanorm** [FoldingAtHome/fah-client-bastet#47]
Hello,

Currently trying this new client. 8.1.2
My setup : virtual machine with 8 cores, 16 GB ram. Ubuntu desktop 22.04 fresh install

When I manually force my full CPU VM to use 8 cores instead of 7 by default, another slot is created.

![2022-10-09_165005](https://user-images.githubusercontent.com/46302945/194763540-d7f132f7-3147-415f-967c-613c6034080c.png)

![2022-10-09_165021](https://user-images.githubusercontent.com/46302945/194763546-cacffab9-7b00-48bf-ba14-11793bae381e.png)

**Comment by jcoffland** [comment]
This is the expected behavior.  There are no "slots" in the v8 client.  The client never changes the resources for a running WU.  This is because there are complicated rules about how many CPUs a WU can use.

One down side is that you will likely get stuck with this allocation because the two WUs are unlikely to ever complete at the same time.  You could pause the client, dump both WUs and unpause.  Then you should get an 8 CPU WU.

**Comment by kbernhagen** [comment]
It is unexpected and user-hostile behavior.

Maybe there could be a max work units option that defaults to 1.

If you change the cpu resource count, the client would delay the change until the next WU is requested.

**Comment by jcoffland** [comment]
The client tries to honor the user's resource allocation.  If the user says I want to use 8 CPUs then we try to make that happen.  If the user were to reduce the number of CPUs to say 6 then the cpu:8 WU would pause due to lack of resources and the client would request a third cpu:5 WU.

One problem with this system is that you end up with WU fragmentation.  I.e. multiple WUs running at the same time.  Alternatively, the client could dump the current set of WUs whenever the resources were changed but that could waste a lot of work.  You could also ask the user if they wanted to wait to apply the change but possibly waiting a couple of days to reduce your CPU/GPU usage seems unreasonable to me.

**Comment by kbernhagen** [comment]
Could ask user if they want to set finishing state on current work before increasing cpus.

That would at least stop additional WUs from starting.
But user would have to manually start folding again after a finish.

**Comment by jcoffland** [comment]
But then you could just go into the finishing state and then change the allocation before unpausing.

**Comment by kbernhagen** [comment]
Yes. Maybe good documentation is the answer.

**Comment by Adanorm** [comment]
I agree with [kbernhagen](https://github.com/kbernhagen) 

I'm working in software too, it's impossible to make proper feedback if we doesn't know the espected behavior.
I'm using FAH since client v4, so I'm used to have some behavior. v7 introduced some. v8 looks like to clear everything ...

It's not natural for users to have a 8 cores CPU and folding by default with 7.
I know the GPU "slot" behavior and the reason of this. But if we want to be accurate, since Core A9 1 pre-allocated core is not enougth. So why 7 ? Why not let the user free ? And why not let the client accept the new configuration, return a message "the change will be applied on next WU", and then after normal finish, let a WU start with new parameters. 
Lots of WU will be dropped unfinished. 

Does this 7 is related to a wrong detection of GPU on my VM without GPU ? If everything is automatic, how are taken the decisions ?

**Comment by kbernhagen** [comment]
The default and max for CPUs is the detected logical cpu count minus one. So the client detected 8 threads for your VM.

**Comment by Adanorm** [comment]
But why this rule Max minus 1 ? I do it when I have a GPU. But when I don't have a GPU, it's mostly wasted.

**Comment by kbernhagen** [comment]
I believe Joseph wants to reserve one thread for the system. GPUs don’t come into play until a WU is assigned.

**Comment by jcoffland** [comment]
We've always had the policy of reserving one CPU for the user by default.

There are several goals we are trying to balance:

  1. When the user requests a change in resource usage it should be honored ASAP.
  2. We no longer want to change resource allocation in the middle of a WU run.
  3. We do not want to throw out any significant amount of completed work.
  4. We want to avoid unnecessary uploads/downloads of WU data.  (i.e. excessive WU dumping)
  5. We want to maximum science results, which should equate to maximizing points.

The ideal solution is the streaming architecture we've discussed but not yet implemented.  In this situation, the client would continually send back small amounts of result data to the WS as it's completed.  Points would be awarded incrementally and a client could continue to work on the same WU for much longer.  The client could end the WU at any time with very little cost.  In this case, we could just stop the current WUs and request a new assignment whenever a resource allocation change was requested.  The problem is that this is a pretty significant change to the client, WS and point system.

**Comment by jcoffland** [comment]
Disabling a GPU always requires stopping the associated WU.  So this issue is only a problem for CPU allocation changes.  Although, it's conceivable that the situation could change in the future.

The reason we don't want to change CPU allocation mid WU run is that the cores, particularly the GROMACS cores, divide the simulation space based on the number of CPUs available.  Some CPU counts don't result in good divisions of the simulation space and will be rejected.  In those cases, the core will actually use less CPUs than requested.  Changing the simulation division mid run is problematic and can result in the simulation failing.  The v7 clients do it anyway.

It may be possible to fix the 0xa9 GROMACS core so that it handles changes in CPU count better.  The core could be restarted and if the CPU count changed it would backup to the last checkpoint and redo the simulation space allocation.
